### ISSUE TITLE
Advice for systems without internet access - no pip install

### ISSUE THREAD

**Issue by mennodeij** [precice/python-bindings#178]
What is the best way to get the Python bindings installed on a system without internet access (internet access disabled for security reasons)? On another system with acces, I can just `pip install --user pyprecice` and it works, but our production cluster gives problems because no internet access.

**Comment by IshaanDesai** [comment]
If there is no internet access, the way to go is [using setup.py](https://github.com/precice/python-bindings#using-setuppy). Please make sure that preCICE is correctly linked, especially if it is installed at a non-standard location,

**Comment by mennodeij** [comment]
Thanks for your help. In the end I chose to do a clean user install with `pip install --user --ignore-cache-dirs --ignore-installed pyprecice`, including all dependencies and Cython, then copied the pyprecice package and its dependencies numpy, mpi4py and Cyhon to the already existing precice module on the system and added the location to PYTHONPATH. 
Now when the user loads the module, the python bindings are also part of the module.

**Comment by BenjaminRodenberg** [comment]
Hi @mennodeij good to hear that you got it working and thank you for the information on what you did! Would you mind opening a Pull Request to add this information also in our docs? You can find an "edit me" button on the top of our documentation page [here](https://precice.org/installation-bindings-python.html). Copy-pasting your comment from the issue here should be sufficient to help others with the same problem getting started.
