### ISSUE TITLE
Version compatibilities

### ISSUE THREAD

**Issue by steffenger** [precice/python-bindings#189]
When I try to install pyprecice with precice version 2.5.0

sudo apt install ./libprecice2_2.5.0_focal.deb
pip3 install --user pyprecice==2.5.0.4

i get the following error

![image](https://github.com/precice/python-bindings/assets/95339856/5bcce56f-9c50-4ab4-8d63-37ebf888cde9)

![image](https://github.com/precice/python-bindings/assets/95339856/97b6c743-7118-4c2d-8062-471920f15893)

I am using WSL/Ubuntu20.04 with python 3.8.10.

According to @IshaanDesai this error is due to version compatibilities.

**Comment by BenjaminRodenberg** [comment]
To me it looks a bit like the preCICE version you are actually using here is too old. Generally pyprecice 2.5.0.4 and preCICE 2.5.0 should work together. Indeed, we forgot to add the corresponding part of the API until 2.5.0.2 (https://github.com/precice/python-bindings/pull/168).

Looking at your logs, I assume you are accidentally using preCICE 2.3.0: In your logs it says `.../precice/SolverInterface.hpp:741:8: note candidate void SolverInterface::readVectorData...`. The location of `readVectorData` matches with preCICE 2.3.0, where it [shows up in line 741](https://github.com/precice/precice/blob/bf3b2cc31619152ab6d2c702777eaf95eb7c53ba/src/precice/SolverInterface.hpp#L741).

Some ideas how to fix this:

* (quick and dirty) If you install pyprecice 2.3.0.1, this should work. `pip3 install --user pyprecice==2.3.0.1`
* (find the root cause of the problem) Try to find out where the preCICE 2.3.0 installation comes from that hides your preCICE 2.5.0 installation. [Our python bindings are using `pkg-config`.](https://github.com/precice/python-bindings/blob/f9498ccd087083c8047782bf55facb2794052713/setup.py#L73) What do you get, when you enter `pkg-config libprecice --cflags`? For me this returns `-I/usr/local/include`. At this location you should also be able to find `/usr/local/include/precice/Version.h` with some information about the installed preCICE version.

@fsimonis any more hints on debugging this?

**Comment by steffenger** [comment]
@BenjaminRodenberg thanks a lot.

i found the V2.3.0 files causing the issue

/usr/local/include/precice$ ls
SolverInterface.hpp  SolverInterfaceC.h  SolverInterfaceFortran.hpp  types.hpp

After removing them, i could install pyprecice==2.5.0.4
But i am wondering why a newer precice version doesnt overwrite those files?

**Comment by fsimonis** [comment]
> But i am wondering why a newer precice version doesnt overwrite those files?

The v2.3.0 files are the result of building and installing preCICE from source. The default installation location/prefix is `/usr/local`, which purpose is to provide system-wide resources managed by the admin, not the package manager.

You then installed the preCICE 2.5.0 Debian package using the package manager, which installs the package in `/usr/`.

So, you end up with two co-existing versions:
* 2.5.0 managed by the package manager in `/usr`
* 2.3.0 managed by you in `/usr/local`

Headers are normally the first instance where this leads to confusion.
