### ISSUE TITLE
Versioning strategy?

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/python-bindings#31]
We decided to have independent versioning for the python bindings and for precice. However, we currently name the application for the python bindings `precice` (see [here](https://github.com/precice/python-bindings/blob/7388d15aea3c9613437d4c62886d400368298252/setup.py#L19)), because we want to call `import precice`. This situation is a bit misleading, since we install (for example) precice version 2.0.0 with version 0.1.0 of the python bindings (that are called precice inside the python world).

How can we

1. have a consistent naming
2. that's not confusing the user and
3. allows us to independntly version precice and the python bindings?

**Comment by BenjaminRueth** [comment]
Strongly related #4, since we have to clear up our minds, before we upload the python bindings (and precice?) to PyPI.

**Comment by MakisH** [comment]
I think the important difference is that the package we install via pip is named e.g. `precice-python-bindings`, so that the user does not get the impression that they also install preCICE with it. This could then have its own package and bindings version.

The python module would then be called `precice`: these are two different things, and they can coexist.

Then, the `getVersionInfo()` should actually give the version of preCICE itself. A separate method could give the version of the bindings.

**Comment by BenjaminRueth** [comment]
Another strategy we might want to consider:

Use Identical version like for preCICE, but declare it an alpha release to make users aware that the interface is not yet stable. See https://www.python.org/dev/peps/pep-0440/#pre-releases.

**Example**: `pyprecice 2.0.0a` provides bindings for `precice 2.0.0`

**Comment by MakisH** [comment]
But this clearly means that it is not released 2.0.0, right? I guess this is fine, but it also assumes that nothing else is changing in the Python bindings themselves, they are completely static apart from the changes necessary to follow preCICE.

It also means that for preCICE 2.0.1 (if any), we will have to release pyprecice 2.0.1a, which may have no changes from pyprecice 2.0.0a.

**Comment by uekerman** [comment]
I am also getting second thoughts about our current versioning suggestion for the bindings. 
Gertjan suggested today that we should follow at least the major version.

Otherwise, we always talk about preCICE v2.0 and then a user downloads the python bindings from pypi and doesn't find a 2.0. Highly confusing. Will a Python user even understand the difference between precice and pyprecice? I am not sure if other packages do this.  

> .. but it also assumes that nothing else is changing in the Python bindings themselves, they are completely static apart from the changes necessary to follow preCICE.

I guess we can assume this, yes, once the Python bindings are "ready". Until then we could increase an alpha counter. `pyprecice 2.0.0.a1`

**Comment by MakisH** [comment]
> Gertjan suggested today that we should follow at least the major version.

It would be nice to be reflected. If we refer to the major version, we should also refer to the feature version: we may have additional API methods.

> Otherwise, we always talk about preCICE v2.0 and then a user downloads the python bindings from pypi and doesn't find a 2.0. Highly confusing.

In principle, the user should not need to try and understand the versions. The package manager (e.g. pip) should know which versions of the bindings need which versions of preCICE. But indeed, it would be nice to be directly related.

> I guess we can assume this, yes, once the Python bindings are "ready". Until then we could increase an alpha counter. `pyprecice 2.0.0.a1`

A mixed scheme would probably be nice. How about something like `pyprecice 0.1.0_precice2.1`? The first is the bindings version, the second the minimum preCICE version supported. Then a package manager can check for `version >= 0.1.0`, and the user can see that this refers to preCICE 2.1.x.

As I wrote in our discussion in the mailing list:
> Similar for the adapters: I now want to change the configuration format of the OpenFOAM adapter, which will be a breaking change for the adapter, but independent of preCICE. I need to bump the major version of the adapter, but not mean anything about preCICE.
>
>From a technical viewpoint, I think every different package (=different repository) should have its own version, increasing the major version if something breaks in its own layer. With this in mind:
>- preCICE API changes from v1 to v2, then bindings get updated to follow it, and then also increase their version independently (e.g. v5 to v6). But since the python-bindings package depends on precice-core, we need to specify this in the package description / pip specifications.
>- OpenFOAM adapter changes the config, increases from v0 to v1. preCICE API changes --> no change in the adapter version.
>
>The users could get confused, but if the users don't need to select versions in the first place (but a package manager), then our problem is solved.

The difference I see between adapters and bindings, is that the bindings should be much less complicated and much more static (when they are ready). So, we don't necessarily need to follow the same principles as in the adapters.

I don't have much experience with versioning systems, so indeed, let's see what other projects are doing / ask experts.

**Comment by uekerman** [comment]
> In principle, the user should not need to try and understand the versions. The package manager (e.g. pip) should know which versions of the bindings need which versions of preCICE. But indeed, it would be nice to be directly related

The whole idea of also installing preCICE with a package manager like pip might give further problems. Let's say you install the python binding and preCICE with pip locally to run Nutils. And you want to couple to OpenFOAM for which you installed preCICE from debian. What happens if both preCICE versions are not the same? :fire: 

> The difference I see between adapters and bindings, is that the bindings should be much less complicated and much more static (when they are ready). So, we don't necessarily need to follow the same principles as in the adapters.

Yes. Another difference between adapters and bindings are that for adapters users might understand why there are different versions. It's a different project which also depends on the OpenFOAM version etc. For bindings, it's not so easy to understand that they are different from preCICE.

**Comment by MakisH** [comment]
> What happens if both preCICE versions are not the same? fire

Isn't this a more general issue, independent of the bindings? We also have it now, as one solver may already be built with a different preCICE version (even as a static library). In many cases, this actually works! :smile:

**Comment by uekerman** [comment]
> Isn't this a more general issue, independent of the bindings?

In principle yes, but not completely, because it means that we cannot let the package manager figure out the correct preCICE version for the bindings. The user has to do this. Ergo: we need sth human understandable.

> We also have it now, as one solver may already be built with a different preCICE version (even as a static library). In many cases, this actually works! 

If they use the same preCICE version, then yes. If they use different versions: :fire: 
And I see also no way that we can support this in the future. Even MPI cannot do this! (btw we depend on MPI).

**Comment by MakisH** [comment]
Then it has just worked by accident some times that I forgot to relink CalculiX? :wink: I always thought it as a feature. They only need to exchange the same kind of messages with the same kind of method. Yes, when we changed from `.address` to `precice-run` I wouldn't expect that to work.

**Comment by fsimonis** [comment]
The versioning also offers post-release versions.
So another option is to keep the precice version identical and append a post version for the bindings.
`2.0.0.post1`

If we use this scheme we could even drop the patch version and only keep major an minor.
`2.1.post2`

**Comment by MakisH** [comment]
I understood that "alpha" was refering to the bindings. In this case, a new version now would be "a2", right?

Dropping the patch version sounds like a good idea.

**Comment by fsimonis** [comment]
I don't understand the rational for using alpha versions for the bindings.

If we link the version of the bindings with the version of preCICE, then it would make sense to use the `.postN` versioning. After all, we release preCICE and **then** the bindings possibly multiple times per preCICE version.

The [versioning scheme](https://www.python.org/dev/peps/pep-0440/#public-version-identifiers) is quite restrictive, so we don't have a lot of choice.
For the post-release, the pep states:

> Note: The use of post-releases to publish maintenance releases containing actual bug fixes is strongly discouraged. In general, it is better to use a longer release number and increment the final component for each maintenance release.

Thus, we could also simply use the full preCICE version and add an additional digit for the python bindings `2.0.0.1`.

**Comment by fsimonis** [comment]
@MakisH @uekerman I opened an issue regarding the differing versions https://github.com/precice/precice/issues/669

**Comment by BenjaminRueth** [comment]
> I don't understand the rational for using alpha versions for the bindings.

The idea behind the alpha versions was to indicate that the python interface is (at least yet) not as stable as the C++ interface. I would like to be able to avoid the situation that we find out that something is not ideal yet and we cannot change it or have to maintain the old version, because we are still in the `2.x.x` release.

At some point in the future, I also want to drop the alpha. But I am not yet sure enough for this step.

**Comment by fsimonis** [comment]
After a phone call with @BenjaminRueth, we realized that we still don't have a good versioning scheme.

The best we can do without adding additional complexity is to use the following scheme:
`Major.Minor.Patch.Binding` e.g `2.0.0.1` for preCICE version `2.0.0` and binding version `1`.
This way, a user can easily install the latest bindings for a precice version:

preCICE version | User enters | Pip installs
--- | --- | ---
`2.0.0` | `pip install pyprecice@2.0.0` | `2.0.0.1`
`2.0.0` | `pip install pyprecice@2.0.0.1` | `2.0.0.1`

Pro :+1: :
1. we can independently version the adapter and release updates
2. users don't need to know the adapter version
3. the versioning always looks the same
4. the user can require a specific adapter version

Con :-1: :
1. we have to release/push/upload a new adapter version for every preCICE version. Even if there are no actual changes in the adapter.
2. the versioning scheme looks unusual

**Comment by uekerman** [comment]
Sounds reasonable to me. But please replace `adapter` with `bindings` above :see_no_evil: . For adapters, we still want to do independent versions. At least that's my current state.

**Comment by MakisH** [comment]
Would the cons be solved by something like `2.0-1` or `2.0_1` (no patch version, different separator)?

I know that the different separator is usually reserved for versions of the package itself (e.g. `libprecice 2.0.0-1`) or for architectures, but maybe this helps.

**Comment by fsimonis** [comment]
@uekerman Oops, I got carried away. :wink: 

@MakisH The versioning is [clearly defined in pep 440](https://www.python.org/dev/peps/pep-0440/#public-version-identifiers), sadly `-` or `_` are not allowed.

**Comment by ajaust** [comment]
I have some questions regarding the bindings and their versioning. Do not get me wrong with all the question/complaining and rather take it as food for thought. Maybe I am not smart enough or missed something in the documentation. I guess many points you might have already discussed internally. ;)

I get that you got for a 4 digit versioning system with the 4th digit being the version of the bindings. I think this is a good/logical way giving the naming convention that you want to follow. However I am a bit confused about the following points:

1. Why is the initial release of the bindings for preCICE `2.0.0` a binding version `2.0.0.1` instead of `2.0.0.0`? Maybe I just need to get used to that convention, but the new preCICE release was `2.0.0` and not `2.0.1`.
2. What is the release schedule of the bindings and how does it affect the compatibility to preCICE bugfixes? preCICE `2.0.2` has been out for some time, but there is not `2.0.2.X` of the bindings yet. Does it mean that there are no compatible bindings yet? Am I supposed to use the `2.0.1.1` bindings (and hope for the best)? Am I forced to use a bugged version of preCICE (i.e. downgrade to preCICE `2.0.1`) if I depend on the preCICE bindings? At the moment (30 April 2020) I am not sure whether I can safely use preCICE `2.0.2` if I want to use the python bindings.
3. In most cases I guess that bugfix releases of preCICE (like `2.0.2`) do not break the compatibility with the bindings. Do you still release a new version of the bindings for all current preCICE version (`2.0.0`, `2.0.1` and `2.0.2`)? 
4. If the bindings stay compatible over several bugfix release, do you only release new version like `2.0.2.X` of the bindings, but then mention that they are still  compatible with previous preCICE releases (like `2.0.0` and `2.0.1`)? In that case the versioning system of the bindings is not that meaningful anymore.
5. Say I am on `2.0.1` and I am not affected to the bug, but also cannot upgrade to `2.0.2` for some reason (no time, complicated to compile stuff etc.). However, I depend on the newest version of the bindings `2.0.2.X`. Maybe there is a crucial bugfix in the bindings of version `2.0.2.X`. Do I have to backport this myself or do I still install the bindings of version `2.0.2.X` and hope for the best?

**Comment by BenjaminRueth** [comment]
Hi Alex,

thanks for the questions. This is really a nice possibility to discuss/explain some decisions regarding our (non-standard) versioning strategy for the python bindings.

Note that we came up with this approach for versioning for the python bindings to solve a very specific problem. Of course, it is to some degree experimental and open to further discussion, since it might contain "bugs". 

> 
> 1. Why is the initial release of the bindings for preCICE `2.0.0` a binding version `2.0.0.1` instead of `2.0.0.0`? Maybe I just need to get used to that convention, but the new preCICE release was `2.0.0` and not `2.0.1`.

The main reason is that it felt a bit odd to start counting at `X.X.X.0` for the bindings version. That's of course not a very strong argument and starting at `2.0.0.0` would also work. If there are good arguments for preferring `2.0.0.0` over `2.0.0.1`, we could, of course, also change this.

> 
> 2. What is the release schedule of the bindings and how does it affect the compatibility to preCICE bugfixes? preCICE `2.0.2` has been out for some time, but there is not `2.0.2.X` of the bindings yet. Does it mean that there are no compatible bindings yet? Am I supposed to use the `2.0.1.1` bindings (and hope for the best)? Am I forced to use a bugged version of preCICE (i.e. downgrade to preCICE `2.0.1`) if I depend on the preCICE bindings? At the moment (30 April 2020) I am not sure whether I can safely use preCICE `2.0.2` if I want to use the python bindings.

We will stick to the release schedule of preCICE. Meaning: If there is a preCICE (feature or major) release, we will also release a new version of the bindings. The update might be trivial, but the main reason to stick to the preCICE release strategy is to keep everyone sane.

> 
> 3. In most cases I guess that bugfix releases of preCICE (like `2.0.2`) do not break the compatibility with the bindings. Do you still release a new version of the bindings for all current preCICE version (`2.0.0`, `2.0.1` and `2.0.2`)?
> 

For bugfix releases of preCICE we do not publish a new version of the bindings. As long as the bug does not affect the bindings. Therefore, the third digit of the bindings version will almost always be a zero (`X.X.0.X`)

> 4. If the bindings stay compatible over several bugfix release, do you only release new version like `2.0.2.X` of the bindings, but then mention that they are still  compatible with previous preCICE releases (like `2.0.0` and `2.0.1`)? In that case the versioning system of the bindings is not that meaningful anymore.

Note that generally all bindings versions `2.X.X.X` should be compatible with preCICE `2.X.X`. This means: No breaking changes within a major release.

I hope this "heals" your comment that the *versioning scheme of the bindings is not that meaningful anymore*.

> 5. Say I am on `2.0.1` and I am not affected to the bug, but also cannot upgrade to `2.0.2` for some reason (no time, complicated to compile stuff etc.). However, I depend on the newest version of the bindings `2.0.2.X`. Maybe there is a crucial bugfix in the bindings of version `2.0.2.X`. Do I have to backport this myself or do I still install the bindings of version `2.0.2.X` and hope for the best?

Our plan in this situation would be to hope for the best and if our versioning strategy works as expected, we should get away with it. 

In case `2.0.2.X` really does **not** work with preCICE `2.0.1` we should try to find out why. I think that in this situation it is very likely that the incompatibility is caused by a bug in `2.0.2.X`.

I hope that the answers help. If not: we can also iterate furtherly! The versioning scheme that we use is far from standard and there are obviously many questions about it to answer.

**Comment by BenjaminRueth** [comment]
I realized that we actually also wanted to release a new version for bugfix releases of preCICE (I fixed my comment above). We have no `v2.0.2.1` for a very simple reason: We just forgot it. I will fix this in a moment.

**Comment by MakisH** [comment]
Releasing a new version of the python bindings even if nothing changed in the bindings sounds also not-so-sane: two versions that are exactly the same, unless the version number change counts as change (a more philosophical questions).

If we keep (let's just keep) this four-digit system this would be natural, but then we need to:
- automate it (or at least remember it)
- document that two versions may be identical in terms of functionality and internal implementation.
