### ISSUE TITLE
Use pkg-config to detect flags

### ISSUE THREAD

**Issue by fsimonis** [precice/python-bindings#5]
It may be worth looking into the [pkgconfig](https://pypi.org/project/pkgconfig/) package.

We could use this to extract the necessary compiler flags for preCICE.

**Comment by BenjaminRueth** [comment]
As far as I understand this issue only the following flags might be provided through `pkgconfig`:

https://github.com/precice/python-bindings/blob/c03e39220bebd3fdd32984e3ccea10bbd2888900/setup.py#L44

The remaining flags have been removed in #36 when we removed MPI. @fsimonis am overseeing something? Do you think that replacing `-lprecice` is worth dealing with `pkgconfig`?

**Comment by MakisH** [comment]
Important note here: pkg-config also returns more than that: it also returns the include path and the library path (apart from the library name). It can be e.g. something like `-I/usr/local/include -L/usr/local/lib -lprecice`.

In your case it probably skips the paths because they are system paths. But it is a very handy tool if you have your dependencies in non-system directories. You just need to make pkg-config aware of the existence of your dependency (e.g. adding the path to `libprecice.pc` file into the `PKG_CONFIG_PATH`).

**Comment by BenjaminRueth** [comment]
Thanks for the info! Sounds like good arguments for keeping this issue open. I will look into it.

**Comment by IshaanDesai** [comment]
Closed via https://github.com/precice/python-bindings/pull/149
